/**
 * The Cloudflare Worker entrypoint — `main` in `wrangler.jsonc`.
 *
 * OpenNext generates `.open-next/worker.js`, which exports only a `fetch` handler. This file
 * wraps it to add the three things a deployment needs and the generated file cannot provide:
 *
 *   1. **A configuration gate.** `loadWorkerEnv()` runs once per isolate, before the first
 *      request is served. It refuses an unsafe `DATA_SOURCE_*` split, a production Worker with
 *      no Cloudflare Access, local upload staging, a missing binding and the rest of its list.
 *      Until this file existed nothing called it, so those checks never ran in a Worker. A
 *      failed check answers every request with 503 and logs the reason, rather than serving
 *      a deployment that fails per request in ways that look like application bugs.
 *   2. **Queue consumers** for `SYNC_QUEUE` and `NOTIFICATION_QUEUE`.
 *   3. **Cron triggers** that enqueue the periodic Drive synchronization and the scheduled
 *      maintenance jobs (`src/server/queues/schedule.ts`).
 *   4. **The `RateLimiter` Durable Object class**, bound as `RATE_LIMITER`.
 *
 * Consumer logic lives in `src/server/queues/consumers.ts` and runs *inside* the Next bundle,
 * reached through an in-process request — see `src/server/queues/internal-token.ts` for why,
 * and for why that request cannot be forged from outside.
 */
import type {
  ExecutionContext,
  MessageBatch,
  Queue,
  ScheduledController,
} from '@cloudflare/workers-types';
// Generated by `opennextjs-cloudflare build`; absent until then, hence no type information.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import openNextWorker from './.open-next/worker.js';
import { assertBindings, loadWorkerEnv } from './src/server/config/env.worker';
import {
  INTERNAL_QUEUE_HEADER,
  INTERNAL_QUEUE_PATH,
  ensureInternalQueueToken,
} from './src/server/queues/internal-token';
import type { ConsumerOutcome, QueueKind } from './src/server/queues/messages';
import { scheduledMessages } from './src/server/queues/schedule';

// Durable Object classes must be exported from the Worker's main module.
export { RateLimiter } from './src/server/auth/rate-limiter.durable-object';

type Env = Record<string, unknown> & { SYNC_QUEUE: Queue; APP_URL?: string };

interface FetchHandler {
  fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response>;
}

const nextHandler = openNextWorker as FetchHandler;

/* ------------------------------------------------------------------ logging */

/** One JSON line per event: Workers Logs indexes the fields. */
function log(level: 'info' | 'warn' | 'error' | 'fatal', msg: string, fields: Record<string, unknown> = {}): void {
  const line = JSON.stringify({ level, msg, source: 'worker-entry', ...fields });
  if (level === 'info') console.log(line);
  else if (level === 'warn') console.warn(line);
  else console.error(line);
}

/* ------------------------------------------------------------------ configuration gate */

/** `undefined` until checked; then `null` (valid) or the reason it is not. Per isolate. */
let configurationError: string | null | undefined;

function stringVars(env: Env): Record<string, string | undefined> {
  const vars: Record<string, string | undefined> = {};
  for (const [key, value] of Object.entries(env)) {
    if (typeof value === 'string') vars[key] = value;
  }
  return vars;
}

function checkConfiguration(env: Env): string | null {
  if (configurationError !== undefined) return configurationError;
  try {
    assertBindings(env);
    const workerEnv = loadWorkerEnv(stringVars(env));
    configurationError = null;
    log('info', 'Worker configuration accepted', {
      nodeEnv: workerEnv.NODE_ENV,
      access: Boolean(workerEnv.CF_ACCESS_TEAM_DOMAIN && workerEnv.CF_ACCESS_AUD),
      malwareScanMode: workerEnv.MALWARE_SCAN_MODE,
    });
    if (workerEnv.MALWARE_SCAN_MODE === 'disabled') {
      log('warn', 'Malware scanning is DISABLED on this deployment', {
        detail: 'MALWARE_SCAN_MODE=disabled: uploads are stored without a malware scan.',
      });
    }
  } catch (error) {
    configurationError = error instanceof Error ? error.message : String(error);
    log('fatal', 'Worker configuration rejected; serving 503 until it is fixed', {
      detail: configurationError,
    });
  }
  return configurationError;
}

function misconfigured(): Response {
  // The reason is in the log, not the response: configuration detail is not for the internet.
  return new Response(
    JSON.stringify({
      error: {
        code: 'SERVICE_MISCONFIGURED',
        message: 'This deployment is not configured correctly. An administrator has been told.',
      },
    }),
    { status: 503, headers: { 'content-type': 'application/json', 'retry-after': '60' } },
  );
}

/* ------------------------------------------------------------------ queues */

function queueKind(queueName: string): QueueKind | null {
  if (queueName.startsWith('biotech-drive-sync-')) return 'sync';
  if (queueName.startsWith('biotech-drive-notifications-')) return 'notifications';
  return null;
}

async function deliver(
  kind: QueueKind,
  message: { id: string; attempts: number; body: unknown },
  env: Env,
  ctx: ExecutionContext,
): Promise<ConsumerOutcome> {
  const origin = typeof env.APP_URL === 'string' ? env.APP_URL : 'http://localhost';
  const request = new Request(new URL(INTERNAL_QUEUE_PATH, origin).toString(), {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      [INTERNAL_QUEUE_HEADER]: ensureInternalQueueToken(),
    },
    body: JSON.stringify({
      queue: kind,
      messageId: message.id,
      attempts: message.attempts,
      body: message.body,
    }),
  });

  const response = await nextHandler.fetch(request, env, ctx);
  if (!response.ok) {
    return {
      outcome: 'retry',
      reason: `consumer route answered ${response.status}`,
      delaySeconds: 60,
    };
  }
  const payload = (await response.json()) as { data?: ConsumerOutcome };
  return payload.data ?? { outcome: 'retry', reason: 'consumer returned no outcome', delaySeconds: 60 };
}

/* ------------------------------------------------------------------ handlers */

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    if (checkConfiguration(env)) return misconfigured();
    return nextHandler.fetch(request, env, ctx);
  },

  async queue(batch: MessageBatch<unknown>, env: Env, ctx: ExecutionContext): Promise<void> {
    const kind = queueKind(batch.queue);
    if (checkConfiguration(env) || !kind) {
      // Not acknowledged: the messages stay queued and are retried, and eventually
      // dead-lettered, rather than being lost to a configuration mistake.
      log('error', 'Queue batch not processed', {
        queue: batch.queue,
        reason: kind ? 'configuration rejected' : 'no consumer for this queue',
        messages: batch.messages.length,
      });
      batch.retryAll({ delaySeconds: 300 });
      return;
    }

    // Sequential on purpose: a sync run is bounded but not small, and two in parallel would
    // contend for the same cursor for no gain. Notification batches are cheap either way.
    for (const message of batch.messages) {
      let result: ConsumerOutcome;
      try {
        result = await deliver(kind, message, env, ctx);
      } catch (error) {
        result = {
          outcome: 'retry',
          reason: error instanceof Error ? error.message : String(error),
          delaySeconds: 60,
        };
      }

      if (result.outcome === 'retry') {
        log('warn', 'Queue message retried', {
          queue: batch.queue,
          messageId: message.id,
          attempts: message.attempts,
          reason: result.reason,
        });
        message.retry({ delaySeconds: result.delaySeconds });
      } else {
        if (result.outcome === 'drop') {
          log('error', 'Queue message dropped', {
            queue: batch.queue,
            messageId: message.id,
            reason: result.reason,
          });
        }
        message.ack();
      }
    }
  },

  async scheduled(controller: ScheduledController, env: Env): Promise<void> {
    if (checkConfiguration(env)) {
      log('error', 'Scheduled run skipped: configuration rejected', { cron: controller.cron });
      return;
    }
    const messages = scheduledMessages(controller.cron, new Date(controller.scheduledTime));
    if (messages.length === 0) {
      log('error', 'Scheduled run ignored: no work is defined for this cron expression', {
        cron: controller.cron,
      });
      return;
    }
    await env.SYNC_QUEUE.sendBatch(messages.map((body) => ({ body })));
    log('info', 'Scheduled work enqueued', {
      cron: controller.cron,
      work: messages.map((message) => (message.kind === 'maintenance.run' ? message.job : message.kind)),
    });
  },
};
